/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  Principiante: [{ type: "autogenerated", dirName: "Principiante" }],
  basico: [{ type: "autogenerated", dirName: "basico-01" }],
  basico2: [{ type: "autogenerated", dirName: "basico-02" }],
  Extra: [{ type: "autogenerated", dirName: "Extra" }],
  Extra02: [{ type: "autogenerated", dirName: "Extra02" }],
  Extra03: [{ type: "autogenerated", dirName: "Extra03" }],
  Extra04: [{ type: "autogenerated", dirName: "Extra04" }],
  preIntermedio: [{ type: "autogenerated", dirName: "pre-intermedio" }],
  intermedio: [{ type: "autogenerated", dirName: "intermedio" }],
};

module.exports = sidebars;
